coverage:
  range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    # project:
    #   default:
    #     target: auto # auto % coverage target
    #     threshold: 5%  # allow for 5% reduction of coverage without failing
    project: false
    patch: false

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: no # [yes :: must have a head report to post]
