# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release deploy

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Job-release echo
        run: echo "foo"
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # #    registry-url: https://registry.npmjs.org/
      # - run: yarn install --frozen-lockfile # yarn 사용시 npm ci 와 같다
      # - run: npm run build
      # - run: npm run test:unit
      # # publish npm
      # - run: echo "hello publish-npm"
      # # - run: npm publish
      # #  env:
      # #    NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      # # publish github pages
      # # - uses: peaceiris/actions-gh-pages@v3
      # #   with:
      # #     github_token: ${{ secrets.GITHUB_TOKEN }}
      # #     publish_dir: './dist'
